// Generated by Vial Keymap C Editor (https://vial-keymap-c-editor.pages.dev)

#include QMK_KEYBOARD_H

#ifdef QMK_SETTINGS
#include "qmk_settings.h"
#endif

/* USER INCLUDE BEGIN */
enum kissbd_keycode {
    IME = QK_KB_0,
    TAB_OPEN,
    TAB_CLOSE,
    TAB_PREV,
    TAB_NEXT,
    TAB_REOPEN,
    WIN_CLOSE,
};
/* USER INCLUDE END */

/* GENERATED CODE BEGIN */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
                 KC_TAB,            KC_Q,            KC_W,            KC_E,
                   KC_R,            KC_T,      KC_MS_BTN1,    KC_LEFT_CTRL,
                   KC_A,            KC_S,            KC_D,            KC_F,
                   KC_G,      KC_MS_BTN3,   KC_LEFT_SHIFT,            KC_Z,
                   KC_X,            KC_C,            KC_V,            KC_B,
              KC_ESCAPE,             IME,     KC_LEFT_GUI,     KC_LEFT_ALT,
                  MO(1),        KC_ENTER,        KC_SPACE,        KC_GRAVE,
                   KC_Y,            KC_U,            KC_I,            KC_O,
                   KC_P,        KC_MINUS,        KC_EQUAL,      KC_MS_BTN2,
                   KC_H,            KC_J,            KC_K,            KC_L,
           KC_SEMICOLON,        KC_QUOTE,    KC_BACKSLASH,            KC_N,
                   KC_M,        KC_COMMA,          KC_DOT,        KC_SLASH,
        KC_LEFT_BRACKET, KC_RIGHT_BRACKET,           MO(2),    KC_BACKSPACE,
             KC_MS_BTN1
    ),
    [1] = LAYOUT(
         KC_TRANSPARENT,            KC_1,            KC_2,            KC_3,
                   KC_4,            KC_5,  KC_TRANSPARENT,  KC_TRANSPARENT,
               TAB_OPEN,       TAB_CLOSE,        TAB_PREV,        TAB_NEXT,
              WIN_CLOSE,  KC_TRANSPARENT,  KC_TRANSPARENT,      TAB_REOPEN,
         KC_TRANSPARENT,   KC_AUDIO_MUTE, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                   KC_6,            KC_7,            KC_8,            KC_9,
                   KC_0,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                KC_LEFT,         KC_DOWN,           KC_UP,        KC_RIGHT,
            KC_WWW_BACK,  KC_WWW_FORWARD,  KC_TRANSPARENT,         KC_HOME,
           KC_PAGE_DOWN,      KC_PAGE_UP,          KC_END,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,       KC_DELETE,
         KC_TRANSPARENT
    ),
    [2] = LAYOUT(
         KC_TRANSPARENT,           KC_F1,           KC_F2,           KC_F3,
                  KC_F4,           KC_F5,           KC_F6,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,           KC_F7,
                  KC_F8,           KC_F9,          KC_F10,          KC_F11,
                 KC_F12,          KC_F13,          KC_F14,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
          QK_BOOTLOADER
    )
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
};
#endif

// Tap Dance definitions
#define TAP_DANCE_ENTRY(onTap, onHold, onDoubleTap, onTapHold, tappingTerm) ((vial_tap_dance_entry_t){.on_tap = onTap, .on_hold = onHold, .on_double_tap = onDoubleTap, .on_tap_hold = onTapHold, .custom_tapping_term = tappingTerm})
#if VIAL_TAP_DANCE_ENTRIES > 0
const vial_tap_dance_entry_t default_tap_dance_entries[] = {
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200)
};
#endif

// Combo definitions
#define COMBO_ENTRY(k1, k2, k3, k4, result) ((vial_combo_entry_t){.input ={k1, k2, k3, k4}, .output = result})
#if VIAL_COMBO_ENTRIES > 0
const vial_combo_entry_t PROGMEM default_combo_entries[] = {
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
#endif

// Macro buffer
const uint8_t PROGMEM default_macro_buffer[] = {

};

// Key Override definitions
#if VIAL_KEY_OVERRIDE_ENTRIES > 0
const vial_key_override_entry_t default_key_override_entries[] = {
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    }
};
#endif

// Initialize Vial dynamic items
void __real_dynamic_keymap_reset(void);
void __wrap_dynamic_keymap_reset(void) {
    __real_dynamic_keymap_reset();

#if VIAL_TAP_DANCE_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_tap_dance_entries) / sizeof(default_tap_dance_entries[0]); ++i) {
        dynamic_keymap_set_tap_dance(i, &default_tap_dance_entries[i]);
    }
#endif
#if VIAL_COMBO_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_combo_entries) / sizeof(default_combo_entries[0]); ++i) {
        dynamic_keymap_set_combo(i, &default_combo_entries[i]);
    }
#endif
#if VIAL_KEY_OVERRIDE_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_key_override_entries) / sizeof(default_key_override_entries[0]); ++i) {
        dynamic_keymap_set_key_override(i, &default_key_override_entries[i]);
    }
#endif
#ifdef QMK_SETTINGS
    qmk_settings_t qs;
    uint8_t* p_qs = (uint8_t*)&qs;
    for (size_t i = 0; i < sizeof(qs); ++i) {
        p_qs[i] = dynamic_keymap_get_qmk_settings(i);
    }
    #ifdef VIAL_DEFAULT_TAPPING
        qs.tapping = VIAL_DEFAULT_TAPPING;
    #endif
    #ifdef VIAL_DEFAULT_AUTO_SHIFT
        qs.auto_shift = VIAL_DEFAULT_AUTO_SHIFT;
    #endif
    #ifdef DEFAULT_GRAVE_ESC_OVERRIDE
        qs.grave_esc_override = DEFAULT_GRAVE_ESC_OVERRIDE;
    #endif

    for (size_t i = 0; i < sizeof(qs); ++i) {
        dynamic_keymap_set_qmk_settings(i, p_qs[i]);
    }

    #ifdef DEFAULT_KEYMAP_EECONFIG
        keymap_config.raw = DEFAULT_KEYMAP_EECONFIG;
        eeconfig_update_keymap(keymap_config.raw);
    #endif

    qmk_settings_init();
#endif

    uint16_t const macro_buffer_size = MIN(sizeof(default_macro_buffer), dynamic_keymap_macro_get_buffer_size());
    dynamic_keymap_macro_set_buffer(0, macro_buffer_size, (uint8_t *)default_macro_buffer);
}

/* GENERATED CODE END */


/* USER CODE BEGIN */
bool process_record_kb(uint16_t keycode, keyrecord_t *record) {
    if (!process_record_user(keycode, record)) {
        return false;
    }

    if (record->event.pressed) {
        switch (keycode) {
            case IME:
                SEND_STRING(SS_LALT(SS_TAP(X_GRAVE)));
                return false;

            case TAB_OPEN:
                SEND_STRING(SS_LCTL(SS_TAP(X_T)));
                return false;

            case TAB_CLOSE:
                SEND_STRING(SS_LCTL(SS_TAP(X_W)));
                return false;

            case TAB_PREV:
                SEND_STRING(SS_LCTL(SS_TAP(X_PGUP)));
                return false;

            case TAB_NEXT:
                SEND_STRING(SS_LCTL(SS_TAP(X_PGDN)));
                return false;

            case TAB_REOPEN:
                SEND_STRING(SS_LCTL(SS_LSFT(SS_TAP(X_T))));
                return false;

            case WIN_CLOSE:
                SEND_STRING(SS_LALT(SS_TAP(X_F4)));
                return false;
        }
    }

    return true;
}

bool is_scroll_mode_enabled = false;

layer_state_t layer_state_set_user(layer_state_t state) {
    is_scroll_mode_enabled = get_highest_layer(state) > 0;
    return state;
}

report_mouse_t pointing_device_task_kb(report_mouse_t mouse_report) {
    if (is_scroll_mode_enabled) {
        mouse_report.h = mouse_report.x;
        mouse_report.v = -mouse_report.y;
        mouse_report.x = 0;
        mouse_report.y = 0;
    }
    return mouse_report;
}
/* USER CODE END */
